n_iter: 1
secs_per_iter: 1

training:
  output_path: dummy
  num_epochs: 10
  learning_rate: 1e-3

hpsearch:  # Used by HyperTrainer
  n_trials: 3
  type: random_uniform
  params:
    -
      param: training.learning_rate
      exponent_base: 10   # 10^x
      lo: -5              # 10^-5
      hi: -2              # 10^-2
